import React, { useEffect, useState } from "react";
import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import Lastinfo from "./LastInfo";
import Middle from "./Middle";
import Top from "./Top";
// import Sider from "./Sider";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [propertydata, setPropertyData] = useState("");
  const [citydata, setCityData] = useState("");

  // useEffect(() => {
  //   getpropertydata();
  // }, []);

  // const getpropertydata = () => {
  //   axios.post("http://localhost:1998/property/Bycity", {}).then((res) => {
  //     setCityData(res?.data?.PropertyDataByCity);
  //     console.log("city", res?.data?.PropertyDataByCity);
  //   });
  // };

  return (
    <>
      <div>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Top />
        {/* <div style={{ display: "flex" }}> */}
        {/* <div style={{ marginTop: "30px", backgroundColor: "gray" }}> */}
        {/* <Sider /> */}
        {/* </div> */}
        {/* <div style={{ marginTop: "30px", marginLeft: "30px" }}> */}
        <Middle />
        {/* </div> */}
        <Lastinfo />
      </div>
    </>
  );
}
